### ISSUE TITLE
[Question] How you got these JS files?

### ISSUE THREAD

**Issue by ranmocy** [jensarps/indexeddb-types#1]
Did you generate them from WebIDL files? Or hand-writing?
Some interface is missing/out-dated. And I'd like to update them.

**Comment by jensarps** [comment]
I did them by hand; I've been looking for a generator, but didn't find one (really, throwing IDL files at a generator that outputs ES5 code, or ES2016, or even TS would be plain awesome…).

Any updates to the definitions are highly appreciated!

**Comment by ranmocy** [comment]
I did look for a generator but still not found last night. So I'm writing one in https://github.com/ranmocy/web-interface
Definitions listed in your project has been generated successfully. A few tiny bugs are fixed.
I'm working on generate the full spec. But surely it's some additional work, like supporting 'enum' or 'dictionary'.

**Comment by jensarps** [comment]
Wow, that's awesome – The generated file looks really good!

Regarding the enum issue: I wonder whether IDEs would understand a string based typedef like this:

```javascript
@typedef {'pending'|'done'} IDBRequestReadyState;
```

JSDoc has an `@enum` tag now – but that doesn't really work like IDL enums like the one above, but instead like real enums in other languages where you get value by property access. Thinking about that – it might actually be a way to document dictionaries…

Anyways, great to see the web-interface project! I have another set of hand-crafted JS definitions, if you want another set to compare: https://github.com/jensarps/fetch-types

**Comment by ranmocy** [comment]
Thanks!
For enum. You need double quote: `@typedef {"pending"|"done"} Type`. There is a feature request to JSDoc project about this actually. But in fact, WebStorm supports this pattern and works well. You can take a look at my screenshot named as "Params validation", which is about enum IDBTransactionMode.

For dictionaries, `@typedef` is better than `@enum`. JSDoc's type definition system is quite powerful. It allow you do define property of a type, which exactly matches WebIDL dictionaries.
